
   
# Docker compose file to start a multi node local test network.
#
# # Nodes
#
# - Validator node A
# - Validator node B
# - Light client C
#
# # Auxiliary nodes
#
# - Prometheus monitoring each node.
# - Grafana pointed at the Prometheus node, configured with all dashboards.
#
# # Usage
#
# 1. Build `target/release/substrate` binary: `cargo build --release`
# 2. Start networks and containers:
#    `sudo docker-compose -f .maintain/sentry-node/docker-compose.yml up`
# 3. Connect to nodes:
#   - validator-a: localhost:9944
#   - validator-b: localhost:9945
#   - light-c: localhost:9946
#   - via polkadot.js/apps: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2Flocalhost%3A<NODE_PORT>#/explorer
#   - grafana: localhost:3001
#   - prometheus: localhost:9090


version: "3.7"
services:

  validator-a:
    ports:
      - "9944:9944"
      - "19933:9933"
    volumes:
      - ./data-a:/data
      - ./chain-spec:/chain-spec
    image: deeper-chain/deeper-chain:latest
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path"
      - "/data"
      - "--chain=/chain-spec/local-dev-raw.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-b/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      - "--rpc-methods=unsafe"

  validator-b:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9945:9944"
      - "29933:9933"
    volumes:
      - ./data-b:/data
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path"
      - "/data"
      - "--chain=/chain-spec/local-dev-raw.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"

  light-c:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9946:9944"
      - "39933:9933"
    volumes:
      - ./data-c:/data
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000003"
      - "--base-path"
      - "/data"
      - "--chain=/chain-spec/local-dev-raw.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-b/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"

networks:
  network-a:
  internet: