[package]
name = "pallet-dynamic-fee"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Dynamic fee handling for EVM."
license = "Apache-2.0"

[dependencies]
pallet-evm = { path = "../evm", version = "5.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
serde = { version = "1.0.101", optional = true }
sp-std = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-core = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-system = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-support = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[dev-dependencies]
pallet-timestamp = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-io = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-inherents/std",
	"frame-system/std",
	"frame-support/std",
	"pallet-evm/std",
]
