[package]
authors = ['deeper.network dev']
edition = '2018'
name = 'pallet-eth-sub-bridge'
version = "3.0.0"
license = "Unlicense"
homepage = "https://deeper.network"
repository = "https://github.com/deeper-chain/deeper-chain"
description = "bridge to transfer DPR tokens between Ethereum and Deeper Chain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev"}
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev"}
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev"}
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev"}
pallet-timestamp = {default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
pallet-balances = { version = "3.0.0", default-features = false, path = "../balances"}
node-primitives = {version = '2.0.0', default-features = false, path = "../../primitives"}
hex-literal = "0.3.1"
# Optional imports for benchmarking
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", optional = true }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-core/std',
	'sp-io/std',
	'sp-std/std',
	'sp-runtime/std',
	'pallet-timestamp/std',
	'pallet-balances/std',
	'node-primitives/std',
	'serde',
]
runtime-benchmarks = [
	"frame-benchmarking",
]